mode: development
media_root: media
media_url: /media
base_url: /
# If your site is nested inside of a bigger one, you can use media_url and
# base_url to properly generate links on your site. For example, if your URL
# will be some.domain.com/starter/, use:
#   media_url: /starter/media
#   base_url: /starter/


template: hyde.ext.templates.jinja.Jinja2Template


plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    # Plugins needed for the advances section.
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.grouper.GrouperPlugin
    - hyde.ext.plugins.tagger.TaggerPlugin

context:
    data:
        website:
            title: Adi Roiban
            author: Adi Roiban
            description: Adi Roiban (aka Roiban Mircea Adrian) personal blog.
            tagline: Who wipes ?
            url: http://adi.roiban.ro
            source_url: https://github.com/adiroiban/adiroiban.github.com
            atom:
                name: RSS Feeds
                url: atom.xml
            menu:
                -
                    name: Home
                    type: page
                    url: index.html
                -
                    name: About me
                    type: page
                    url: about.html
                -
                    name: My belief
                    type: page
                    url: belief.html

            # Official tags listed in the sidebar.
            tags:
                -
                    title: English
                    name: english
                    description: Posts in English
                -
                    title: Romanian
                    name: romanian
                    description: Posts in Romanian
                -
                    title: Python
                    name: python
                    description: Posts about Python
                -
                    title: Free Software
                    name: free-software
                    description: Free Software
                -
                    title: Planet GNOME
                    name: planet-gnome
                    description: Planet GNOME
                -
                    title: Planet Ubuntu
                    name: planet-ubuntu
                    description: Planet Ubuntu

            # Badges that will be displayed in the sidebar.
            badges:
                -
                    name: Animal Liberation Human Liberation
                    url: http://en.wikipedia.org/wiki/Animal_liberation_movement
                    image: img/liberation.jpg
                -
                    name: Reduce Reuse Recycle
                    url: http://en.wikipedia.org/wiki/Waste_hierarchy
                    image: img/reduce-reuse-recycle.jpg
                -
                    name: CouchSurfing
                    url: http://www.couchsurfing.org/
                    image: img/cs.png
                -
                    name: Reactie in Lant
                    url: http://www.reactieinlant.ro/
                    image: img/reactieinlant.gif
        links:
            g_plus:
                url: https://plus.google.com/u/0/114870316061271703771/posts

meta:
    nodemeta: meta.yaml
    default_block: content
    ga_tracking_code: UA-2942924-1
    skip_navigation: False


sorter:
    name:
        attr: name
        filters:
            source_file.kind: html
            # You can include only files from a certain folder.
            #resource.node: (name of the folder)

    file_type:
        attr: 
            - source_file.kind
            - source_file.size

    created:
        attr: meta.created
        filters:
            source_file.kind: html

    latest:
        attr: meta.updated
        filters:
            source_file.kind: html
            meta.skip_navigation: False
        reverse: True


grouper:
    # Category grouper is a selection of tags which will be listed in
    # menu.
    category:
        sorter: name
        description: Post cagetory
        groups:
            - name: English
              tag: english
              description: Posts in English
            - name: Romanian
              tag: romanian
              description: Posts in Romanian
            - name: Python
              tag: python
              description: Posts about Python
            - name: Free Software
              tag: free-software
              description: Free Software
            - name: Planet GNOME
              tag: planet-gnome
              description: Planet GNOME
            - name: Planet Ubuntu
              tag: planet-ubuntu
              description: Planet Ubuntu


tagger:
    sorter: latest
    archives:
        blog:
            target: tags
            template: tagged_posts.j2
            archive_extension: html
            meta:
                skip_navigation: True
